<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace SendgridBundle\Entity\Definition;

/**
 * Definition class for the Alert connector object
 *
 */
trait AlertDefinition
{    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $type;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $emailTo;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $percentage;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $frequency;
	
    

	
	/**
	 * Get type
	 *
	 * @return string
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Set type
	 *
	 * @param  string $type
	 * @return Alert
	 */
	public function setType($type)
	{
		$this->type = $type;
		
		return $this;
	}	
    

	
	/**
	 * Get emailTo
	 *
	 * @return string
	 */
	public function getEmailTo()
	{
		return $this->emailTo;
	}

	/**
	 * Set emailTo
	 *
	 * @param  string $emailTo
	 * @return Alert
	 */
	public function setEmailTo($emailTo)
	{
		$this->emailTo = $emailTo;
		
		return $this;
	}	
    

	
	/**
	 * Get percentage
	 *
	 * @return integer
	 */
	public function getPercentage()
	{
		return $this->percentage;
	}

	/**
	 * Set percentage
	 *
	 * @param  integer $percentage
	 * @return Alert
	 */
	public function setPercentage($percentage)
	{
		$this->percentage = $percentage;
		
		return $this;
	}	
    

	
	/**
	 * Get frequency
	 *
	 * @return string
	 */
	public function getFrequency()
	{
		return $this->frequency;
	}

	/**
	 * Set frequency
	 *
	 * @param  string $frequency
	 * @return Alert
	 */
	public function setFrequency($frequency)
	{
		$this->frequency = $frequency;
		
		return $this;
	}	
}