<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace SendgridBundle\Entity\Definition;

/**
 * Definition class for the Bounce connector object
 *
 */
trait BounceDefinition
{    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $startTime;
	
    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $endTime;
	
    

	
	/**
	 * Get startTime
	 *
	 * @return datetime
	 */
	public function getStartTime()
	{
		return $this->startTime;
	}

	/**
	 * Set startTime
	 *
	 * @param  datetime $startTime
	 * @return Bounce
	 */
	public function setStartTime($startTime)
	{
		$this->startTime = $startTime;
		
		return $this;
	}	
    

	
	/**
	 * Get endTime
	 *
	 * @return datetime
	 */
	public function getEndTime()
	{
		return $this->endTime;
	}

	/**
	 * Set endTime
	 *
	 * @param  datetime $endTime
	 * @return Bounce
	 */
	public function setEndTime($endTime)
	{
		$this->endTime = $endTime;
		
		return $this;
	}	
}