<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace SendgridBundle\Entity\Definition;

/**
 * Definition class for the InvalidEmail connector object
 *
 */
trait InvalidEmailDefinition
{    


	private $startTime;    


	private $endTime;    


	private $limit;    


	private $offset;    

	public function setStartTime($startTime)
	{
		$this->startTime = $startTime;
		
		return $this;
	}
	
	public function getStartTime()
	{
		return $this->startTime;
	}
    

	public function setEndTime($endTime)
	{
		$this->endTime = $endTime;
		
		return $this;
	}
	
	public function getEndTime()
	{
		return $this->endTime;
	}
    

	public function setLimit($limit)
	{
		$this->limit = $limit;
		
		return $this;
	}
	
	public function getLimit()
	{
		return $this->limit;
	}
    

	public function setOffset($offset)
	{
		$this->offset = $offset;
		
		return $this;
	}
	
	public function getOffset()
	{
		return $this->offset;
	}
}