<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace SendgridBundle\Entity\Definition;

/**
 * Definition class for the Personalizations connector object
 *
 */
trait PersonalizationsDefinition
{    


	private $email;    


	private $subject;    

	public function setEmail($email)
	{
		$this->email = $email;
		
		return $this;
	}
	
	public function getEmail()
	{
		return $this->email;
	}
    

	public function setSubject($subject)
	{
		$this->subject = $subject;
		
		return $this;
	}
	
	public function getSubject()
	{
		return $this->subject;
	}
}