<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace SendgridBundle\Entity\Definition;

/**
 * Definition class for the Send connector object
 *
 */
trait SendDefinition
{    

	 /**
	 * @var Object
	 *
	 
	 */
	
	private $personalizations;
	
    

	 /**
	 * @var Object
	 *
	 
	 */
	
	private $fromEmail;
	
    

	 /**
	 * @var Object
	 *
	 
	 */
	
	private $content;
	
    

	
	/**
	 * Get personalizations
	 *
	 * @return Object
	 */
	public function getPersonalizations()
	{
		return $this->personalizations;
	}

	/**
	 * Set personalizations
	 *
	 * @param  Object $personalizations
	 * @return Send
	 */
	public function setPersonalizations($personalizations)
	{
		$this->personalizations = $personalizations;
		
		return $this;
	}	
    

	
	/**
	 * Get fromEmail
	 *
	 * @return Object
	 */
	public function getFromEmail()
	{
		return $this->fromEmail;
	}

	/**
	 * Set fromEmail
	 *
	 * @param  Object $fromEmail
	 * @return Send
	 */
	public function setFromEmail($fromEmail)
	{
		$this->fromEmail = $fromEmail;
		
		return $this;
	}	
    

	
	/**
	 * Get content
	 *
	 * @return Object
	 */
	public function getContent()
	{
		return $this->content;
	}

	/**
	 * Set content
	 *
	 * @param  Object $content
	 * @return Send
	 */
	public function setContent($content)
	{
		$this->content = $content;
		
		return $this;
	}	
}