<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace SendgridBundle\Entity\Definition;

/**
 * Definition class for the SubUser connector object
 *
 */
trait SubUserDefinition
{    


	private $limit;    


	private $offset;    


	private $username;    

	public function setLimit($limit)
	{
		$this->limit = $limit;
		
		return $this;
	}
	
	public function getLimit()
	{
		return $this->limit;
	}
    

	public function setOffset($offset)
	{
		$this->offset = $offset;
		
		return $this;
	}
	
	public function getOffset()
	{
		return $this->offset;
	}
    

	public function setUsername($username)
	{
		$this->username = $username;
		
		return $this;
	}
	
	public function getUsername()
	{
		return $this->username;
	}
}