<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace SendgridBundle\Entity\Definition;

/**
 * Definition class for the SubUser connector object
 *
 */
trait SubUserDefinition
{    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $limit;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $offset;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $username;
	
    

	
	/**
	 * Get limit
	 *
	 * @return integer
	 */
	public function getLimit()
	{
		return $this->limit;
	}

	/**
	 * Set limit
	 *
	 * @param  integer $limit
	 * @return SubUser
	 */
	public function setLimit($limit)
	{
		$this->limit = $limit;
		
		return $this;
	}	
    

	
	/**
	 * Get offset
	 *
	 * @return integer
	 */
	public function getOffset()
	{
		return $this->offset;
	}

	/**
	 * Set offset
	 *
	 * @param  integer $offset
	 * @return SubUser
	 */
	public function setOffset($offset)
	{
		$this->offset = $offset;
		
		return $this;
	}	
    

	
	/**
	 * Get username
	 *
	 * @return string
	 */
	public function getUsername()
	{
		return $this->username;
	}

	/**
	 * Set username
	 *
	 * @param  string $username
	 * @return SubUser
	 */
	public function setUsername($username)
	{
		$this->username = $username;
		
		return $this;
	}	
}