<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace SendgridBundle\Entity\Definition;

/**
 * Definition class for the User connector object
 *
 */
trait UserDefinition
{    


	private $address;    


	private $city;    


	private $company;    


	private $country;    


	private $firstName;    


	private $lastName;    


	private $phone;    


	private $state;    


	private $website;    


	private $zip;    


	private $email;    


	private $type;    


	private $reputation;    


	private $username;    


	private $userId;    


	private $remain;    


	private $total;    


	private $overage;    


	private $used;    


	private $lastReset;    


	private $nextReset;    


	private $resetFrequency;    


	private $newPassword;    


	private $oldPassword;    

	public function setAddress($address)
	{
		$this->address = $address;
		
		return $this;
	}
	
	public function getAddress()
	{
		return $this->address;
	}
    

	public function setCity($city)
	{
		$this->city = $city;
		
		return $this;
	}
	
	public function getCity()
	{
		return $this->city;
	}
    

	public function setCompany($company)
	{
		$this->company = $company;
		
		return $this;
	}
	
	public function getCompany()
	{
		return $this->company;
	}
    

	public function setCountry($country)
	{
		$this->country = $country;
		
		return $this;
	}
	
	public function getCountry()
	{
		return $this->country;
	}
    

	public function setFirstName($firstName)
	{
		$this->firstName = $firstName;
		
		return $this;
	}
	
	public function getFirstName()
	{
		return $this->firstName;
	}
    

	public function setLastName($lastName)
	{
		$this->lastName = $lastName;
		
		return $this;
	}
	
	public function getLastName()
	{
		return $this->lastName;
	}
    

	public function setPhone($phone)
	{
		$this->phone = $phone;
		
		return $this;
	}
	
	public function getPhone()
	{
		return $this->phone;
	}
    

	public function setState($state)
	{
		$this->state = $state;
		
		return $this;
	}
	
	public function getState()
	{
		return $this->state;
	}
    

	public function setWebsite($website)
	{
		$this->website = $website;
		
		return $this;
	}
	
	public function getWebsite()
	{
		return $this->website;
	}
    

	public function setZip($zip)
	{
		$this->zip = $zip;
		
		return $this;
	}
	
	public function getZip()
	{
		return $this->zip;
	}
    

	public function setEmail($email)
	{
		$this->email = $email;
		
		return $this;
	}
	
	public function getEmail()
	{
		return $this->email;
	}
    

	public function setType($type)
	{
		$this->type = $type;
		
		return $this;
	}
	
	public function getType()
	{
		return $this->type;
	}
    

	public function setReputation($reputation)
	{
		$this->reputation = $reputation;
		
		return $this;
	}
	
	public function getReputation()
	{
		return $this->reputation;
	}
    

	public function setUsername($username)
	{
		$this->username = $username;
		
		return $this;
	}
	
	public function getUsername()
	{
		return $this->username;
	}
    

	public function setUserId($userId)
	{
		$this->userId = $userId;
		
		return $this;
	}
	
	public function getUserId()
	{
		return $this->userId;
	}
    

	public function setRemain($remain)
	{
		$this->remain = $remain;
		
		return $this;
	}
	
	public function getRemain()
	{
		return $this->remain;
	}
    

	public function setTotal($total)
	{
		$this->total = $total;
		
		return $this;
	}
	
	public function getTotal()
	{
		return $this->total;
	}
    

	public function setOverage($overage)
	{
		$this->overage = $overage;
		
		return $this;
	}
	
	public function getOverage()
	{
		return $this->overage;
	}
    

	public function setUsed($used)
	{
		$this->used = $used;
		
		return $this;
	}
	
	public function getUsed()
	{
		return $this->used;
	}
    

	public function setLastReset($lastReset)
	{
		$this->lastReset = $lastReset;
		
		return $this;
	}
	
	public function getLastReset()
	{
		return $this->lastReset;
	}
    

	public function setNextReset($nextReset)
	{
		$this->nextReset = $nextReset;
		
		return $this;
	}
	
	public function getNextReset()
	{
		return $this->nextReset;
	}
    

	public function setResetFrequency($resetFrequency)
	{
		$this->resetFrequency = $resetFrequency;
		
		return $this;
	}
	
	public function getResetFrequency()
	{
		return $this->resetFrequency;
	}
    

	public function setNewPassword($newPassword)
	{
		$this->newPassword = $newPassword;
		
		return $this;
	}
	
	public function getNewPassword()
	{
		return $this->newPassword;
	}
    

	public function setOldPassword($oldPassword)
	{
		$this->oldPassword = $oldPassword;
		
		return $this;
	}
	
	public function getOldPassword()
	{
		return $this->oldPassword;
	}
}